import { Step, Steps } from "fumadocs-ui/components/steps";
import defaultMdxComponents from "fumadocs-ui/mdx";
import type { MDXComponents } from "mdx/types";
import { BenchBars } from "@/components/mdx/bench-bars";
import {
  AgentSourceTimeline,
  AuditChurn,
  BacklogFeel,
  BinarySizeWaterfall,
  CellShape,
  ClipWidth,
  ClusterExplorer,
  DaemonTilePlacement,
  DividerCollide,
  ExtentScan,
  HardTabHole,
  HeadlessTerm,
  HelpKeyDrift,
  InboxDemo,
  InvariantBlind,
  JsonByteLoss,
  KeptTestBar,
  KeybindingExplorer,
  KeycastDemo,
  LayoutModes,
  LineDiscipline,
  LinkLanes,
  MailboxSandbox,
  MediumProbe,
  NegativeControlBench,
  PaneBoxNegotiation,
  PreshapedGuard,
  QueryPath,
  RatioDrift,
  ReattachReplay,
  ReleaseClip,
  RenderPathAttrs,
  ReviewWalkthrough,
  ScrollbackBytes,
  ScrollColumnsRoundTrip,
  SendKeysTokens,
  SessionDiagram,
  ShapingCompare,
  SharedBordersToggle,
  ShrinkRace,
  SpentFrames,
  StartupPreview,
  StyleIdRecycle,
  TapeTrustFlow,
  TestPurgeStages,
  ToleranceBlind,
  WindowTargetOrder,
} from "@/components/mdx/lazy";
import { Mermaid } from "@/components/mdx/mermaid";
import { RunTally } from "@/components/mdx/run-tally";
import { TerminalCapture } from "@/components/mdx/terminal-capture";

export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...defaultMdxComponents,
    // The same wrapper as fumadocs, which scrolls a wide table on a phone.
    // It takes focus, so a keyboard can scroll it too.
    table: (props) => (
      <div
        // biome-ignore lint/a11y/noNoninteractiveTabindex: a region that scrolls must be reachable by keyboard
        tabIndex={0}
        className="prose-no-margin relative my-6 overflow-auto focus:outline-none focus-visible:ring-2 focus-visible:ring-fd-primary"
      >
        <table {...props} />
      </div>
    ),
    Step,
    Steps,
    Mermaid,
    InboxDemo,
    KeybindingExplorer,
    LayoutModes,
    ReviewWalkthrough,
    SessionDiagram,
    BacklogFeel,
    BenchBars,
    DividerCollide,
    RatioDrift,
    ToleranceBlind,
    LineDiscipline,
    ShrinkRace,
    ClusterExplorer,
    RunTally,
    TerminalCapture,
    TapeTrustFlow,
    StartupPreview,
    ShapingCompare,
    DaemonTilePlacement,
    KeycastDemo,
    SharedBordersToggle,
    InvariantBlind,
    LinkLanes,
    CellShape,
    SpentFrames,
    ScrollColumnsRoundTrip,
    ExtentScan,
    RenderPathAttrs,
    AuditChurn,
    HelpKeyDrift,
    PreshapedGuard,
    MediumProbe,
    StyleIdRecycle,
    QueryPath,
    SendKeysTokens,
    ClipWidth,
    PaneBoxNegotiation,
    AgentSourceTimeline,
    MailboxSandbox,
    ReattachReplay,
    ScrollbackBytes,
    WindowTargetOrder,
    HeadlessTerm,
    HardTabHole,
    NegativeControlBench,
    JsonByteLoss,
    BinarySizeWaterfall,
    TestPurgeStages,
    KeptTestBar,
    ReleaseClip,
    ...components,
  };
}
