import { changed, on, ran, seq, whenState } from "../matchers";
import type { Track } from "../types";

/** For someone who has never used a multiplexer. */
export const basics: Track = {
  id: "basics",
  title: "The basics",
  blurb: "Windows, typing, tiling and workspaces, from zero.",
  audience: "New here",
  minutes: 5,
  next: ["from-tmux"],
  steps: [
    {
      id: "open-window",
      title: "Open a window",
      note: "You start in window mode.",
      keys: ["n"],
      needs: "window",
      done: on("window.open"),
      hint: "Click the dark area first, then press n.",
      learned: "new window",
    },
    {
      id: "start-typing",
      title: "Start typing in it",
      note: "i switches to typing mode.",
      keys: ["i"],
      needs: "window",
      done: changed("mode", "terminal"),
      hint: "Press i. The badge flips to TYPING.",
      learned: "typing mode",
    },
    {
      id: "run-neofetch",
      title: "Say hi to the shell",
      note: "Keys now go to the program.",
      keys: [{ text: "neofetch" }, "enter"],
      needs: "terminal",
      done: ran("neofetch"),
      hint: "Type neofetch and press enter.",
      showMe: "neofetch\r",
      learned: "run a command",
    },
    {
      id: "window-mode",
      title: "Back to window mode",
      note: "ctrl+b is the leader key.",
      keys: ["ctrl+b", "esc"],
      done: changed("mode", "window"),
      hint: "Hold ctrl and tap b. Let go. Then press esc.",
      learned: "window mode",
    },
    {
      id: "second-window",
      title: "Open a second window",
      note: "Tiling makes room for it.",
      keys: ["n"],
      needs: "window",
      done: on("window.open", (e) => (e.state?.windows ?? 0) >= 2),
      hint: "In window mode, n opens a window.",
      learned: "new window",
    },
    {
      id: "hop",
      title: "Hop between windows",
      keys: ["tab"],
      needs: "window",
      done: on("window.focus", (e) => Boolean(e.data?.to)),
      hint: "Tab moves the focus to the next window.",
      learned: "next window",
    },
    {
      id: "zoom",
      title: "Zoom in, then out",
      keys: ["z", "z"],
      needs: "window",
      done: seq(changed("window.zoom", true), changed("window.zoom", false)),
      hint: "Press z to zoom the window. Press z again to put it back.",
      learned: "zoom",
    },
    {
      id: "tile",
      title: "Snap them into tiles",
      note: "We scattered them for you.",
      keys: ["t"],
      needs: "window",
      setup: [{ command: "cascade", wait: 400 }],
      done: changed("tiling", true),
      hint: "Press t to turn tiling back on.",
      learned: "tiling",
    },
    {
      id: "workspace",
      title: "Visit workspace 2",
      note: "Nine desktops, one terminal.",
      keys: ["ctrl+b", "w", "2"],
      done: changed("workspace", 2),
      hint: "ctrl+b, then w, then 2. Your windows wait on workspace 1.",
      learned: "workspaces",
    },
    {
      id: "home",
      title: "Come back home",
      keys: ["ctrl+b", "w", "1"],
      done: whenState((s) => s.workspace === 1 && s.windows > 0),
      hint: "ctrl+b, then w, then 1.",
      learned: "workspaces",
    },
    {
      id: "palette",
      title: "Find any command",
      note: "When you forget a key, look here.",
      keys: ["ctrl+p", "esc"],
      done: seq(
        changed("commandPalette", true),
        changed("commandPalette", false),
      ),
      hint: "ctrl+p opens the palette. Esc closes it.",
      learned: "command palette",
    },
    {
      id: "detach",
      title: "Leave it running",
      keys: ["ctrl+b", "d"],
      hint: "",
      explainer: {
        art: "detach",
        body: "In a real terminal, ctrl+b d detaches. Your windows keep running in the background. Run tuios again and they are all back.",
        href: "/docs/sessions",
        linkText: "How sessions work",
      },
      learned: "detach",
    },
  ],
};
