import { changed, on, seq, via } from "../matchers";
import type { Track } from "../types";

/** For tmux users: what carries over, and the few keys that differ. */
export const fromTmux: Track = {
  id: "from-tmux",
  title: "Coming from tmux",
  blurb: "Your fingers already know most of it. Here is what changes.",
  audience: "tmux users",
  minutes: 3,
  next: ["basics"],
  setup: [
    { command: "newWindow", wait: 250 },
    { command: "mode", args: ["terminal"] },
  ],
  steps: [
    {
      id: "new-window",
      title: "New window",
      note: "Same as tmux.",
      keys: ["ctrl+b", "c"],
      done: on("window.open"),
      hint: "Hold ctrl and tap b, let go, then press c.",
      learned: "new window",
    },
    {
      id: "split-right",
      title: "Split right",
      note: "tmux used %. Here it is |.",
      keys: ["ctrl+b", "|"],
      done: via(["prefix_split_vertical"], on("window.open")),
      hint: "| is shift and backslash. The plain backslash works too.",
      learned: "split right",
    },
    {
      id: "split-down",
      title: "Split down",
      note: 'tmux used ". Here it is -.',
      keys: ["ctrl+b", "-"],
      done: via(["prefix_split_horizontal"], on("window.open")),
      hint: "ctrl+b, then the minus key.",
      learned: "split down",
    },
    {
      id: "move",
      title: "Move between panes",
      note: "Same arrows as tmux.",
      keys: ["ctrl+b", "left"],
      done: via(
        [
          "terminal_focus_left",
          "terminal_focus_right",
          "terminal_focus_up",
          "terminal_focus_down",
        ],
        on("window.focus"),
      ),
      hint: "ctrl+b, then any arrow key.",
      learned: "move focus",
    },
    {
      id: "zoom",
      title: "Zoom in, then out",
      note: "Same as tmux.",
      keys: ["ctrl+b", "z", "ctrl+b", "z"],
      done: seq(changed("window.zoom", true), changed("window.zoom", false)),
      hint: "ctrl+b z zooms. Do it again to unzoom.",
      learned: "zoom",
    },
    {
      id: "close",
      title: "Close a pane",
      note: "Same as tmux, minus the y/n prompt.",
      keys: ["ctrl+b", "x"],
      done: on("window.close"),
      hint: "ctrl+b, then x.",
      learned: "close",
    },
    {
      id: "window-mode",
      title: "Meet window mode",
      note: "New: a mode with no prefix at all.",
      keys: ["ctrl+b", "esc"],
      done: changed("mode", "window"),
      hint: "ctrl+b, then esc. The badge flips to WINDOWS.",
      learned: "window mode",
    },
    {
      id: "float",
      title: "Tile what floats",
      note: "New: windows can float. We scattered them.",
      keys: ["t"],
      needs: "window",
      setup: [{ command: "cascade", wait: 400 }],
      done: changed("tiling", true),
      hint: "In window mode, t toggles tiling.",
      learned: "tiling",
    },
    {
      id: "workspace",
      title: "Jump to workspace 2",
      note: "Like tmux windows, but nine whole desktops.",
      keys: ["ctrl+b", "w", "2"],
      done: changed("workspace", 2),
      hint: "ctrl+b, then w, then 2.",
      learned: "workspaces",
    },
    {
      id: "detach",
      title: "Detach, same as ever",
      keys: ["ctrl+b", "d"],
      hint: "",
      explainer: {
        art: "detach",
        body: "ctrl+b d detaches, like tmux. tuios attach brings you back, even from another machine over SSH.",
        href: "/docs/sessions",
        linkText: "Sessions and attach",
      },
      learned: "detach",
    },
  ],
};
