import { changed, moved, on, seq, via, zoomed } from "../matchers";
import type { Track } from "../types";

/** BSP, master-stack, the scrolling strip, zoom and floating windows. */
export const layouts: Track = {
  id: "layouts",
  title: "Layouts",
  blurb: "Tiles, a master and a stack, a scrolling strip, and floats.",
  audience: "Tidy minds",
  minutes: 5,
  next: ["workspaces", "power-moves"],
  setup: [
    { command: "newWindow", wait: 250 },
    { command: "newWindow", wait: 250 },
    { command: "mode", args: ["window"] },
  ],
  steps: [
    {
      id: "preselect",
      title: "Choose where it lands",
      note: "alt and h, j, k or l picks the side. Then n.",
      keys: ["alt+j", "n"],
      needs: "window",
      done: seq(
        on("action", (e) => String(e.data?.name).startsWith("preselect_")),
        on("window.open"),
      ),
      hint: "Hold alt (option on a Mac), tap j, let go. Then n. The new window opens below.",
      learned: "preselect",
    },
    {
      id: "rotate",
      title: "Rotate the split",
      note: "Side by side becomes stacked, and back.",
      keys: ["R"],
      needs: "window",
      done: via(["rotate_split"], moved()),
      hint: "Capital R, so shift and r.",
      learned: "rotate",
    },
    {
      id: "swap",
      title: "Swap two windows",
      note: "Capital H, J, K, L push the window that way.",
      keys: ["H"],
      needs: "window",
      done: via(["swap_left", "swap_right", "swap_up", "swap_down"], moved()),
      hint: "Shift and h swaps left. Try L if nothing is to the left.",
      learned: "swap",
    },
    {
      id: "master",
      title: "Master and stack",
      note: "One big window on the left, the rest stacked on the right.",
      keys: ["ctrl+p", { text: "master" }, "enter"],
      done: changed("layout", "master-stack"),
      hint: "ctrl+p opens the palette. Type master and press enter.",
      learned: "master-stack",
    },
    {
      id: "ratio",
      title: "Grow the master",
      note: "> grows it, < shrinks it.",
      keys: [">", ">"],
      needs: "window",
      done: via(["resize_master_grow", "resize_master_shrink"], moved()),
      hint: "> is shift and the period key.",
      learned: "master ratio",
    },
    {
      id: "scrolling",
      title: "The scrolling strip",
      note: "Columns on an endless strip. New ones slide in, nothing shrinks.",
      keys: ["ctrl+p", { text: "scrolling" }, "enter"],
      done: changed("layout", "scrolling"),
      hint: "ctrl+p, type scrolling, press enter.",
      learned: "scrolling",
    },
    {
      id: "column-width",
      title: "Widen a column",
      note: "The strip scrolls to keep it in view.",
      keys: [">", ">"],
      needs: "window",
      done: via(["resize_master_grow", "resize_master_shrink"], moved()),
      hint: "> widens the column, < narrows it.",
      learned: "column width",
    },
    {
      id: "zoom",
      title: "Zoom in, then out",
      keys: ["z", "z"],
      needs: "window",
      done: seq(zoomed(true), zoomed(false)),
      hint: "z zooms the window. z again puts it back.",
      learned: "zoom",
    },
    {
      id: "float",
      title: "Let them float, then snap",
      note: "t turns tiling off. h and l snap to a half.",
      keys: ["t", "h"],
      needs: "window",
      done: seq(
        changed("tiling", false),
        via(["snap_left", "snap_right"], moved()),
      ),
      hint: "t floats every window. Then h snaps this one to the left half. Drag them with the mouse too.",
      learned: "float and snap",
    },
  ],
};
