import { changed, closed, on, opened, seq, via } from "../matchers";
import type { Track } from "../types";
import { sampleWindow } from "./scenes";

/** Nine workspaces, moving windows between them, and the session rail. */
export const workspaces: Track = {
  id: "workspaces",
  title: "Workspaces and the rail",
  blurb: "Nine desktops in one terminal, and a rail that shows it all.",
  audience: "Many projects",
  minutes: 4,
  next: ["agents", "power-moves"],
  setup: [
    { command: "newWindow", wait: 250 },
    { command: "newWindow", wait: 250 },
    { command: "mode", args: ["window"] },
  ],
  steps: [
    {
      id: "visit",
      title: "Visit workspace 2",
      note: "Your two windows wait on workspace 1.",
      keys: ["ctrl+b", "w", "2"],
      done: changed("workspace", 2),
      hint: "ctrl+b, then w, then 2. The dock at the bottom shows where you are.",
      learned: "switch workspace",
    },
    {
      id: "fill",
      title: "Make it yours",
      note: "Each workspace has its own windows and layout.",
      keys: ["n"],
      needs: "window",
      done: on("window.open", (e) => e.data?.workspace === 2),
      hint: "In window mode, n opens a window here.",
      learned: "new window",
    },
    {
      id: "back",
      title: "Jump straight back",
      note: "alt and a number skips the prefix.",
      keys: ["alt+1"],
      done: changed("workspace", 1),
      hint: "Hold alt (option on a Mac) and press 1. If the browser takes it, ctrl+b w 1 does the same.",
      learned: "alt+number",
    },
    {
      id: "send",
      title: "Send a window away",
      note: "Shift and a number moves the window, and you follow it.",
      keys: ["ctrl+b", "w", "#"],
      done: via(
        [
          "workspace_prefix_move_1",
          "workspace_prefix_move_2",
          "workspace_prefix_move_3",
          "workspace_prefix_move_4",
          "workspace_prefix_move_5",
          "workspace_prefix_move_6",
          "workspace_prefix_move_7",
          "workspace_prefix_move_8",
          "workspace_prefix_move_9",
        ],
        on("workspace"),
      ),
      hint: "ctrl+b, w, then shift and 3, which is #.",
      learned: "move window",
    },
    {
      id: "rail",
      title: "Open the rail",
      note: "Sessions, windows, agents and files, at a glance.",
      keys: ["ctrl+b", "b"],
      done: opened("sidebar"),
      hint: "ctrl+b, then b. The rail opens on the left.",
      learned: "rail",
    },
    {
      id: "walk-rail",
      title: "Walk the rail",
      note: "s steps in. j and k move, enter jumps there.",
      keys: ["s", "j", "j", "enter"],
      needs: "window",
      done: seq(
        on("action", (e) => e.data?.name === "focus_sidebar"),
        on("workspace"),
      ),
      hint: "Press s. j twice lands on the first window, the one marked w1. Enter takes you there.",
      learned: "rail keys",
    },
    {
      id: "switcher",
      title: "See every workspace",
      note: "A picker with a preview of each one.",
      keys: ["ctrl+b", "W", "enter"],
      done: seq(opened("workspaceSwitcher"), closed("workspaceSwitcher")),
      hint: "ctrl+b, then capital W. Arrows pick one, enter goes there.",
      learned: "workspace switcher",
    },
    {
      id: "remote",
      title: "Every session, every machine",
      keys: ["ctrl+b", "S"],
      setup: sampleWindow("sessions", "tuios ls"),
      hint: "",
      explainer: {
        art: "remote",
        body: "On your machine the rail lists every session, and sessions on your other machines too. ctrl+b S switches between them.",
        href: "/docs/session-rail",
        linkText: "The session rail",
      },
      learned: "sessions",
    },
  ],
};
